### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by jvhellemond** [Heydon/fukol-grids#1]
This framework is missing a package.json so I can `npm install` it. Otherwise I'm gonna have to, I don't know, just copy-paste all of it or something.

Also you should like totally semver this so I can statically link it into my BootstrapReactFukol™ hybrid fork.

**Comment by holger1411** [comment]
I agree!
I think a good project needs a minimum of 50.000 files in its /node_module directory.
And this project hasn´t even a /node_modules folder...
Oh, and whats about a Bower version? Can´t find a bower.js...

**Comment by emilyTK** [comment]
No need for a node_modules folder when you have a package.json.
This is a valid request.

**Comment by jvhellemond** [comment]
Yeah, I'm gonna close this issue. I think the maintainer of this repo has just stopped caring. #sad
