### ISSUE TITLE
Problem in Internet Explorer 11

### ISSUE THREAD

**Issue by martinpesout** [Heydon/fukol-grids#15]
Hi, if you test it in IE 11, you can see that final look is just a bit broken. Some grid items overflow row width:

![snimek obrazovky 2016-10-14 v 8 09 28](https://cloud.githubusercontent.com/assets/239468/19377325/c09b5d64-91e5-11e6-88f4-942bf57f43af.png)

This problem is easy to fix. You cannot use padding for grid items but you have to add one more element inside each item and apply padding on such element. See:

![snimek obrazovky 2016-10-14 v 8 08 05](https://cloud.githubusercontent.com/assets/239468/19377341/e12aeb4e-91e5-11e6-9d2f-f38e2140724e.png)

**Comment by Heydon** [comment]
I'll write a note. Thanks!
