### ISSUE TITLE
Logo is a bit penisy

### ISSUE THREAD

**Issue by Munter** [Heydon/fukol-grids#3]
Normally I enjoy the odd penis logo here and there, but 5 in the same logo seems a bit much.

I really want to use this framework in the current bigcorp in employed in, but I suspect the legal review might also notice the penises and not want to be associated with them

**Comment by Heydon** [comment]
That is not a cluster of penises. It's a sea anemone. This may contradict things I stated in the FAQ section. I'm sure it'll all be sorted out before version 0.0.0.0.0.0.0.0.0.1.

**Comment by levidurfee** [comment]
It's a good logo, Bront.

**Comment by Munter** [comment]
Oh of course it is! You know that feeling that when you see something you just can't unsee it? Sea anemone!

Thanks for the swift reply. I'm sure my legal team will have no problems with it now!
