### ISSUE TITLE
Demo maybe ?

### ISSUE THREAD

**Issue by Naereen** [Heydon/fukol-grids#4]
You should include one / possibly many demos of your framework.

**Comment by JoanClaret** [comment]
codepen examples would be appreciated

**Comment by Heydon** [comment]
I'm working on something. In the meantime, the README shows how it works with a gif.

**Comment by Heydon** [comment]
Hi @JoanClaret, there's a codePen now (referenced in the README).

See http://codepen.io/heydon/pen/dpzwVd.

**Comment by JoanClaret** [comment]
Great! thank you!
