### ISSUE TITLE
The dicks seem kinda virile

### ISSUE THREAD

**Issue by domdavis** [Heydon/fukol-grids#5]
You claim the dicks in the logo are a "bunch of old dicks", however, I'd expect _old_ dicks to be less... upright.

**Comment by Heydon** [comment]
Thank you for your concern, @domdavis . I was simply using the _"load of old x"_ construction. See also _"load of old wank"_ and _"load of old dingo's kidneys"_.

**Comment by domdavis** [comment]
Excellent, carry on then 👍
